/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import Controller.NguoiDungManager;
import Controller.Saver;
import com.mycompany.model.SinhVien;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tienanh03
 */
public class DanhSachSV extends javax.swing.JFrame {
    DefaultTableModel model;
    /**
     * Creates new form DanhSachSV
     */
    public DanhSachSV() {
        initComponents();
        try {
 
            initTable();
        } catch (ClassNotFoundException ex) {
            
        } catch (SQLException ex) {
            
        }
    }
    public void initTable() throws ClassNotFoundException, SQLException{
        NguoiDungManager ng=new NguoiDungManager();
        model=new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"Mã Sinh Viên","Họ Tên","Email","Số Điện Thoại","Giới Tính","Địa Chỉ"});
        List<SinhVien> list=ng.layDSSV();
        list.forEach(item->{
        model.addRow(new Object[]{item.getMaSV(),item.getHoTen(),item.getEmail(),item.getSdt(),item.getGioiTinh()==1?"Nam":"Nữ",item.getDiaChi()});
        });
        JTB.setModel(model);
    }
    public void lammoi() throws ClassNotFoundException, SQLException{
        NguoiDungManager ng=new NguoiDungManager();
        model=new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"Mã Sinh Viên","Họ Tên","Email","Số Điện Thoại","Giới Tính","Địa Chỉ"});
        List<SinhVien> list=ng.layDSSV();
        list.forEach(item->{
        model.addRow(new Object[]{item.getMaSV(),item.getHoTen(),item.getEmail(),item.getSdt(),item.getGioiTinh()==1?"Nam":"Nữ",item.getDiaChi()});
        });
        model.fireTableDataChanged();
        JTB.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTB = new javax.swing.JTable();
        JT1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JT2 = new javax.swing.JTextField();
        JB1 = new javax.swing.JButton();
        JB2 = new javax.swing.JButton();
        JB3 = new javax.swing.JButton();
        JB4 = new javax.swing.JButton();
        JL2 = new javax.swing.JLabel();
        JB9 = new javax.swing.JButton();
        JB5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTB.setEnabled(false);
        jScrollPane1.setViewportView(JTB);

        JT1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        JT1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JT1.setText("DANH SÁCH SINH VIÊN");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("MÃ SINH VIÊN: ");

        JB1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JB1.setText("Tìm Kiếm");
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });

        JB2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JB2.setText("Sửa");
        JB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB2ActionPerformed(evt);
            }
        });

        JB3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JB3.setForeground(new java.awt.Color(255, 51, 0));
        JB3.setText("Xóa");
        JB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB3ActionPerformed(evt);
            }
        });

        JB4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JB4.setText("THÊM");
        JB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB4ActionPerformed(evt);
            }
        });

        JL2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        JL2.setForeground(new java.awt.Color(255, 51, 0));

        JB9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JB9.setText("LÀM MỚI");
        JB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB9ActionPerformed(evt);
            }
        });

        JB5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JB5.setText("MÔN HỌC");
        JB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JB5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JB4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(324, 324, 324)
                        .addComponent(JB9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JL2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JT2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JB1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JB2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JB3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 424, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB1)
                    .addComponent(JB2)
                    .addComponent(JB3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JL2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB9)
                    .addComponent(JB5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JT1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(380, 380, 380))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JT1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean check(){
        boolean ok=false;
        String regex="[0-9]{10}";
        if(JT2.getText().equalsIgnoreCase("")){
            ok=true;
            JL2.setText("Mã Sinh Viên Không Được Để Trống!");
        }
        else if(!JT2.getText().matches(regex)){
            ok=true;
            JL2.setText("Mã Sinh Viên Không Hợp Lệ!");
        }
         else{
            JL2.setText("");
        }
        return ok;
    }
    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
        // TODO add your handling code here:
        if(check()){
            return;
        }
        else{
            try {
               SinhVienForm svf=new SinhVienForm(JT2.getText());
            svf.setLocationRelativeTo(null);
            svf.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Không Tìm Thấy!");
            }
            
        }
       
    }//GEN-LAST:event_JB1ActionPerformed

    private void JB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB4ActionPerformed
        // TODO add your handling code here:
        GiaoVienQL ql=new GiaoVienQL();
       ql.setLocationRelativeTo(null);
       ql.setVisible(true);
    }//GEN-LAST:event_JB4ActionPerformed
    public boolean checkmsv(String msv){
        boolean ok=false;
        try {
            NguoiDungManager ndm=new NguoiDungManager();
            if(ndm.timKiem(msv)==null){
                ok=true;
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DanhSachSV.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DanhSachSV.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return ok;
    }
    private void JB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB3ActionPerformed
        // TODO add your handling code here:
        if(check()){
            return;
        }
        else if(checkmsv(JT2.getText())){
            JOptionPane.showMessageDialog(rootPane, "Không Tìm Thấy");
            return;
        }
        else{
            try {
                NguoiDungManager ngm=new NguoiDungManager();
                if(JOptionPane.showConfirmDialog(this, "Bạn Có muốn xóa không?")==JOptionPane.NO_OPTION){
                    return;
                }
                else{
                    ngm.Xoa(JT2.getText());
                     
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Không Tìm Thấy Mã SV Muốn Xóa!");
            }
        }
    }//GEN-LAST:event_JB3ActionPerformed

    private void JB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB9ActionPerformed
        try {
            // TODO add your handling code here:
            lammoi();
        } catch (ClassNotFoundException ex) {
           
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_JB9ActionPerformed

    private void JB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB2ActionPerformed
        // TODO add your handling code here:
         if(check()){
            return;
        }
        else{
           try {
             NguoiDungManager ndm=new NguoiDungManager();
            SuaTT stt=new SuaTT(ndm.timKiem(JT2.getText()));
            stt.setLocationRelativeTo(null);
            stt.setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Không Tìm Thấy!");
            }
            
        }
        
    }//GEN-LAST:event_JB2ActionPerformed

    private void JB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB5ActionPerformed
        // TODO add your handling code here:
       DSMH dsmh=new DSMH();
       dsmh.setLocationRelativeTo(null);
       dsmh.setVisible(true);
    }//GEN-LAST:event_JB5ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB1;
    private javax.swing.JButton JB2;
    private javax.swing.JButton JB3;
    private javax.swing.JButton JB4;
    private javax.swing.JButton JB5;
    private javax.swing.JButton JB9;
    private javax.swing.JLabel JL2;
    private javax.swing.JLabel JT1;
    private javax.swing.JTextField JT2;
    private javax.swing.JTable JTB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
