/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import Controller.NguoiDungManager;
import com.mycompany.model.Mon;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tienanh03
 */
public class DSMH extends javax.swing.JFrame {
    DefaultTableModel model;
    JOptionPane jp;
    /**
     * Creates new form DSMH
     */
    public DSMH() {
        initComponents();
        initTable();
    }
    public boolean check(){
        boolean ok=false;
        String reMMH="M\\d{3}";
        String reTC="\\d";
        if(JT1.getText().equalsIgnoreCase("")){
             ok=true;
            JL5.setText("Không được để trống!");
        }
        else if(!JT1.getText().matches(reMMH)){
             ok=true;
            JL5.setText("Không Hợp lệ!");
        }
        else{
             JL5.setText("");
        }
        if(JT2.getText().equalsIgnoreCase("")){
             ok=true;
            JL6.setText("Không được để trống!");
        }
        else{
             JL6.setText("");
        }
        if(JT3.getText().equalsIgnoreCase("")){
             ok=true;
            JL7.setText("Không được để trống!");
        }
        else if(!JT3.getText().matches(reTC)){
             ok=true;
            JL7.setText("Không Hợp lệ!");
        }
        else{
             JL7.setText("");
        }
        return ok;
    }
    public void initTable(){
 
        model= new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"Mã Môn Học","Tên Môn Học","Số Tín Chỉ"});
        try {
            NguoiDungManager ndm=new NguoiDungManager();
             List<Mon> list = new ArrayList<>();
             list=ndm.layDSMH();
             list.forEach(item->{
                 model.addRow(new Object[]{item.getMaMH(),item.getTenMH(),item.getSoTC()});
             });
             JTB.setModel(model);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DSMH.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DSMH.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTB = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JT1 = new javax.swing.JTextField();
        JT2 = new javax.swing.JTextField();
        JT3 = new javax.swing.JTextField();
        JB1 = new javax.swing.JButton();
        JB2 = new javax.swing.JButton();
        JB3 = new javax.swing.JButton();
        JL5 = new javax.swing.JLabel();
        JL6 = new javax.swing.JLabel();
        JL7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH MÔN HỌC");

        JTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTB.setEnabled(false);
        jScrollPane1.setViewportView(JTB);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mã Môn Học:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tên Môn Học:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Số Tín Chỉ:");

        JT1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        JT2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        JT3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        JB1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JB1.setForeground(new java.awt.Color(255, 51, 0));
        JB1.setText("XÓA");
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });

        JB2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JB2.setText("SỬA");
        JB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB2ActionPerformed(evt);
            }
        });

        JB3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JB3.setText("THÊM");
        JB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB3ActionPerformed(evt);
            }
        });

        JL5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        JL5.setForeground(new java.awt.Color(255, 51, 0));

        JL6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        JL6.setForeground(new java.awt.Color(255, 51, 0));

        JL7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        JL7.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(408, 408, 408))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JL6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JL5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JT1)
                    .addComponent(JT2)
                    .addComponent(JT3, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(JL7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(326, 326, 326)
                .addComponent(JB1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JB3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JB1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JB2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JB3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JL5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JL6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JL7)
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean checkMH(String maMH){
        boolean ok=false;
        try {
            NguoiDungManager ndm=new NguoiDungManager();
            if(!ndm.timkiemMH(maMH)){
                ok=true;
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DSMH.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DSMH.class.getName()).log(Level.SEVERE, null, ex);
        }
        return ok;
    }
    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
        // TODO add your handling code here:
        String reMMH="M\\d{3}";
        if(JT1.getText().equalsIgnoreCase("")){
            JL5.setText("Không được để trống!");
        }
        else if(checkMH(JT1.getText().trim())){
            JOptionPane.showMessageDialog(rootPane, "Không tìm thấy!");
        }
          else if(!JT1.getText().matches(reMMH)){
            JL5.setText("Không Hợp lệ!");
        }
        else{
            JL5.setText("");
            try {
                NguoiDungManager ndm=new NguoiDungManager();
                if(JOptionPane.showConfirmDialog(this, "Bạn Có muốn xóa không?")==JOptionPane.NO_OPTION){
                    return;
                }
                else{
                   ndm.xoaMH(JT1.getText().trim(), jp);
                    initTable();
                }
            
             
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(DSMH.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(DSMH.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_JB1ActionPerformed

    private void JB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB3ActionPerformed
        // TODO add your handling code here:
        if(check()){
            
        }
        else{
            try {
                NguoiDungManager ndm=new NguoiDungManager();
                Mon m=new Mon();
                m.setMaMH(JT1.getText());
                m.setTenMH(JT2.getText());
                m.setSoTC(Integer.parseInt(JT3.getText()));
                if(ndm.ThemMH(m, jp)){
                     JOptionPane.showMessageDialog(this, "THÊM THÀNH CÔNG");
                     initTable();
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(DSMH.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(DSMH.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_JB3ActionPerformed

    private void JB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB2ActionPerformed
        // TODO add your handling code here:
        if(check()){
            
        }
        else if(checkMH(JT1.getText().trim())){
            JOptionPane.showMessageDialog(rootPane, "Không tìm thấy!");
        }
        else{
            try {
                NguoiDungManager ndm=new NguoiDungManager();
                Mon m=new Mon();
                m.setMaMH(JT1.getText());
                m.setTenMH(JT2.getText());
                m.setSoTC(Integer.parseInt(JT3.getText()));
                if(ndm.SuaMH(m, jp)){
                     JOptionPane.showMessageDialog(this, "SỬA THÀNH CÔNG");
                     initTable();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Không Tìm Thấy!");
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(DSMH.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(DSMH.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_JB2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB1;
    private javax.swing.JButton JB2;
    private javax.swing.JButton JB3;
    private javax.swing.JLabel JL5;
    private javax.swing.JLabel JL6;
    private javax.swing.JLabel JL7;
    private javax.swing.JTextField JT1;
    private javax.swing.JTextField JT2;
    private javax.swing.JTextField JT3;
    private javax.swing.JTable JTB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
