/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.view;

import Controller.NguoiDungManager;
import com.mycompany.connect.ConnectionSQL;
import com.mycompany.model.BangDiem;
import com.mycompany.model.SinhVien;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tienanh03
 */
public class SuaTT extends javax.swing.JFrame {

    NguoiDungManager nd;
    DefaultTableModel model;
    JOptionPane jp;

    /**
     * Creates new form SinhVienForm
     */
    public SuaTT(SinhVien sv) {
        initComponents();
        JT1.setText(sv.getMaSV());
        JT2.setText(sv.getHoTen());
        JT3.setText(sv.getEmail());
        JT4.setText(sv.getSdt());
        JT5.setText(sv.getDiaChi());
        if(sv.getGioiTinh()==1){
            JR1.setSelected(true);
        }
        else{
            JR2.setSelected(true);
        }
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JT1 = new javax.swing.JTextField();
        JT2 = new javax.swing.JTextField();
        JT3 = new javax.swing.JTextField();
        JT5 = new javax.swing.JTextField();
        JT4 = new javax.swing.JTextField();
        JR1 = new javax.swing.JRadioButton();
        JR2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        JT11 = new javax.swing.JLabel();
        JT12 = new javax.swing.JLabel();
        JL13 = new javax.swing.JLabel();
        JL14 = new javax.swing.JLabel();
        JL15 = new javax.swing.JLabel();
        JL16 = new javax.swing.JLabel();
        JL8 = new javax.swing.JLabel();
        JL9 = new javax.swing.JLabel();
        JL10 = new javax.swing.JLabel();
        JL11 = new javax.swing.JLabel();
        JL12 = new javax.swing.JLabel();
        jlabel13 = new javax.swing.JLabel();
        JB1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JTF1 = new javax.swing.JTextField();
        JTF2 = new javax.swing.JTextField();
        JBT2 = new javax.swing.JButton();
        JBT1 = new javax.swing.JButton();
        JLB1 = new javax.swing.JLabel();
        JLB2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thông Tin Sinh Viên");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mã Sinh Viên:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Họ Tên:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Giới Tính:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Địa Chỉ");

        JT1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JT1.setEnabled(false);
        JT1.setFocusable(false);

        JT2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        JT3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        JT5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        JT4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        buttonGroup1.add(JR1);
        JR1.setText("Nam");

        buttonGroup1.add(JR2);
        JR2.setText("Nữ");
        JR2.setRequestFocusEnabled(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("SĐT: ");

        JL13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        JL13.setForeground(new java.awt.Color(255, 51, 0));

        JL14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        JL14.setForeground(new java.awt.Color(255, 51, 0));

        JL15.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        JL15.setForeground(new java.awt.Color(255, 51, 0));

        JL16.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        JL16.setForeground(new java.awt.Color(255, 51, 0));

        JL8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        JL8.setForeground(new java.awt.Color(255, 51, 0));

        JL9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        JL9.setForeground(new java.awt.Color(255, 51, 0));

        JL10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        JL10.setForeground(new java.awt.Color(255, 0, 0));

        JL11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        JL11.setForeground(new java.awt.Color(255, 0, 0));

        JL12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        JL12.setForeground(new java.awt.Color(255, 0, 0));

        jlabel13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jlabel13.setForeground(new java.awt.Color(255, 0, 0));

        JB1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JB1.setText("SỬA");
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Mã Môn Học:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Điểm: ");

        JTF1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        JTF2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        JBT2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBT2.setText("Thêm");
        JBT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT2ActionPerformed(evt);
            }
        });

        JBT1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBT1.setText("Sửa");
        JBT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT1ActionPerformed(evt);
            }
        });

        JLB1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        JLB1.setForeground(new java.awt.Color(255, 51, 0));

        JLB2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        JLB2.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JLB2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JLB1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JTF2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(JBT1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBT2)
                .addGap(140, 140, 140))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(JLB1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(JTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLB2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBT2)
                    .addComponent(JBT1))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JT2)
                            .addComponent(JT1)
                            .addComponent(JT3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JR1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JR2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JL13, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JL14, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JL16, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JL15, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JT4, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                                    .addComponent(JL8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JT5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JL9, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JT11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(380, 380, 380)
                                .addComponent(JT12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JL10, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(JL11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JL12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(JB1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JL13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(JL14)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(JL16)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(JT4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JR1)
                            .addComponent(JR2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JL15, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JL8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JT5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JL9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(JL10)
                        .addGap(34, 34, 34)
                        .addComponent(JL11)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JL12)
                                .addGap(38, 38, 38)
                                .addComponent(jlabel13))
                            .addComponent(JB1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JT11)
                            .addComponent(JT12))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
        // TODO add your handling code here:
        if (check()) {
            return;
        } else {
            try {
                NguoiDungManager ngm = new NguoiDungManager();
                SinhVien sv = new SinhVien();
                sv.setMaSV(JT1.getText());
                sv.setHoTen(JT2.getText());
                sv.setEmail(JT3.getText());
                sv.setSdt(JT4.getText());
                sv.setDiaChi(JT5.getText());
                sv.setGioiTinh(JR1.isSelected() ? 1 : 0);
                if (ngm.Sua(sv)) {
                    JOptionPane.showMessageDialog(this, "SỬA THÀNH CÔNG");
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Thất Bại!");
            }
        }
    }//GEN-LAST:event_JB1ActionPerformed

    private void JBT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT2ActionPerformed
        // TODO add your handling code here:
        if(check2()){

        }
        else{
            try {
                NguoiDungManager ndm=new NguoiDungManager();
                ndm.themDiem(JT1.getText().trim(), JTF1.getText().trim(), Double.parseDouble(JTF2.getText()));
            } catch(Exception e){
                JOptionPane.showConfirmDialog(rootPane, "Không Có Mã Môn Học Này!");
            }
        }

    }//GEN-LAST:event_JBT2ActionPerformed

    private void JBT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT1ActionPerformed
        // TODO add your handling code here:
        if(check2()){

        }
        else{
            try {
                NguoiDungManager ndm=new NguoiDungManager();
                ndm.suaDiem(Double.parseDouble(JTF2.getText()), JTF1.getText(), JT1.getText());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GiaoVienQL.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(GiaoVienQL.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_JBT1ActionPerformed
    public boolean check() {
        boolean ok = false;
        String reSDT = "0\\d{9}";
        String reEmail = "^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@"
                + "[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
        //a
        if (JT4.getText().equalsIgnoreCase("")) {
            JL8.setText("Không được để trống!");
            ok = true;
        } else if (!JT4.getText().trim().matches(reSDT)) {
            ok = true;
            JL8.setText("SĐT không hợp lệ!");
        } else {
            JL8.setText("");
        }
        //b
        if (JT2.getText().equalsIgnoreCase("")) {
            ok = true;
            JL14.setText("Không được để trống!");
        } else {
            JL14.setText("");
        }
        if (JT3.getText().equalsIgnoreCase("")) {
            JL16.setText("Không được để trống!");
            ok = true;
        } else if (!JT3.getText().trim().matches(reEmail)) {
            JL16.setText("email không hợp lệ!");
            ok = true;
        } else {
            JL16.setText("");
        }
        if (JR1.isSelected() || JR2.isSelected()) {
            JL15.setText("");
        } else {
            ok = true;
            JL15.setText("Không được để trống!");
        }
        if (JT5.getText().equalsIgnoreCase("")) {
            JL9.setText("Không được để trống!");
            ok = true;
        } else {
            JL9.setText("");
        }

        return ok;
    }
     public boolean check2(){
        boolean ok=false;
        String reMMH="M\\d{3}";
        if(JTF1.getText().equalsIgnoreCase("")){
            JLB1.setText("Không được để trống!");
            ok=true;
        }
        else if(!JTF1.getText().trim().matches(reMMH)){
            JLB1.setText("Không hợp lệ!");
            ok=true;
        }
        else{
            JLB1.setText("");
        }
        String rediem="a-zA-Z";
         if(JTF2.getText().equalsIgnoreCase("")){
            JLB2.setText("Không được để trống!");
            ok=true;
        }
        else if(JTF2.getText().trim().matches(rediem)||(Double.parseDouble(JTF2.getText())<0||Double.parseDouble(JTF2.getText())>10)){
            JLB2.setText("Không hợp lệ!");
            ok=true;
        }
        else{
            JLB2.setText("");
        }
        return ok;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB1;
    private javax.swing.JButton JBT1;
    private javax.swing.JButton JBT2;
    private javax.swing.JLabel JL10;
    private javax.swing.JLabel JL11;
    private javax.swing.JLabel JL12;
    private javax.swing.JLabel JL13;
    private javax.swing.JLabel JL14;
    private javax.swing.JLabel JL15;
    private javax.swing.JLabel JL16;
    private javax.swing.JLabel JL8;
    private javax.swing.JLabel JL9;
    private javax.swing.JLabel JLB1;
    private javax.swing.JLabel JLB2;
    private javax.swing.JRadioButton JR1;
    private javax.swing.JRadioButton JR2;
    private javax.swing.JTextField JT1;
    private javax.swing.JLabel JT11;
    private javax.swing.JLabel JT12;
    private javax.swing.JTextField JT2;
    private javax.swing.JTextField JT3;
    private javax.swing.JTextField JT4;
    private javax.swing.JTextField JT5;
    private javax.swing.JTextField JTF1;
    private javax.swing.JTextField JTF2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlabel13;
    // End of variables declaration//GEN-END:variables
}
